# ============================================================
#  Sven — Seven OS Package Manager
#  HANS TECH © 2024 — GPL v3
#  installer/hooks.py — Post-install package hooks & translation
# ============================================================
#
#  Reads `.INSTALL` scriptlets. Automatically translates Arch
#  `systemctl` commands into `SysVinit` equivalents.
#  Runs global ldconfig, cache updates securely.
# ============================================================

import os
import subprocess
from pathlib import Path

from ..config import get_config
from ..exceptions import HookError, HookTranslationError

# Standard Arch auto-hooks that we manually execute
AUTO_HOOKS = [
    ["ldconfig"],
    ["update-desktop-database", "-q"],
    ["update-mime-database", "/usr/share/mime"],
    ["gtk-update-icon-cache", "-q", "-t", "-f", "/usr/share/icons/hicolor"],
    ["fc-cache", "-s"],
    ["glib-compile-schemas", "/usr/share/glib-2.0/schemas"],
]

def run_auto_hooks(install_root: str = None):
    """Run standard desktop/system cache updates after a transaction."""
    root = install_root or get_config().install_root
    
    print("\n   [Hooks] Running global system updates...")
    for cmd in AUTO_HOOKS:
        # Check if binary exists in root
        bin_path = Path(root) / cmd[0].lstrip("/")
        # Some are just in PATH, let's use shutil.which or try-except
        
        try:
            # We don't fail the install if a hook binary is entirely missing 
            # (e.g. headless server doesn't have gtk-update-icon-cache)
            subprocess.run(
                cmd,
                root_dir=root if root != "/" else None,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=30
            )
        except (FileNotFoundError, OSError):
            continue


class HookRunner:
    def __init__(self, pkg_name: str, install_file: str, is_aur: bool = False):
        self.pkg_name = pkg_name
        self.install_file = install_file
        self.is_aur = is_aur
        self.config = get_config()

    def run_phase(self, phase: str, version: str, old_version: str = ""):
        """
        Execute a specific phase function in the .install script.
        E.g. post_install, pre_upgrade.

        If the environment uses SysVinit, we intercept systemctl.
        """
        path = Path(self.install_file)
        if not path.exists():
            return

        # Read the script to find systemctl commands
        script_content = path.read_text(errors="replace")
        translated_content = self._translate_systemctl(script_content)

        # We write a temporary runner script to handle the bash sourcing
        runner_script = path.with_name(f".{self.pkg_name}_{phase}.sh")
        
        bash_wrapper = f"""#!/bin/bash
# Hook wrapper generated by Sven
{translated_content}

if type {phase} >/dev/null 2>&1; then
    {phase} {version} {old_version}
fi
"""
        runner_script.write_text(bash_wrapper)
        runner_script.chmod(0o755)

        print(f"   [Hooks] Running {phase} for {self.pkg_name}...")
        
        try:
            # Drop capabilities for AUR hooks if running as root
            env = os.environ.copy()
            cmd = [str(runner_script)]
            
            # (For safety on actual LFS, we'd use `sudo -u nobody` here if is_aur
            # but usually package install hooks NEED root to write to /etc/ or /var/lib.
            # Sven's hook_scanner stops malicious rm -rf / before we get here).

            result = subprocess.run(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                env=env,
                timeout=120
            )

            # Log hook output safely
            if result.stdout.strip():
                self._log_hook_output(phase, result.stdout)

            if result.returncode != 0:
                print(f"   ⚠ Hook {phase} returned non-zero status ({result.returncode})")

        except subprocess.TimeoutExpired:
            print(f"   ⚠ Hook {phase} timed out after 120s")
        finally:
            if runner_script.exists():
                runner_script.unlink()

    def _translate_systemctl(self, script: str) -> str:
        """
        Translates Arch Linux `systemctl` native commands to SysVinit / OpenRC 
        depending on Seven OS config.
        """
        init_sys = self.config.init_system
        if init_sys == "systemd":
            return script # no translation needed

        lines = script.splitlines()
        translated = []

        for line in lines:
            stripped = line.strip()
            if stripped.startswith("systemctl") or " systemctl " in stripped:
                translated.append(self._convert_systemd_line(stripped, init_sys))
            else:
                translated.append(line)

        return "\n".join(translated)

    def _convert_systemd_line(self, line: str, init_sys: str) -> str:
        """Convert a single line containing `systemctl`."""
        parts = line.split()
        if "systemctl" not in parts:
            return line

        idx = parts.index("systemctl")
        if idx + 2 >= len(parts):
            # Probably daemon-reload or status
            if "daemon-reload" in parts:
                return line.replace("systemctl daemon-reload", ":") # Do nothing mapped to true/colon
            return line
            
        action = parts[idx + 1]
        service = parts[idx + 2]
        
        # Strip .service
        if service.endswith(".service"):
            service = service[:-8]

        # sysvinit translation
        if init_sys == "sysvinit":
            if action == "enable":
                # Assuming update-rc.d or rc-update
                res = f"rc-update add {service} default"
            elif action == "disable":
                res = f"rc-update del {service}"
            elif action in ("start", "stop", "restart", "status"):
                res = f"/etc/init.d/{service} {action}"
            else:
                # Unsupported action
                res = ":"
        else:
            # fallback
            res = ":"

        # reconstruct
        new_parts = parts[:idx] + [res] + parts[idx+3:]
        return " ".join(new_parts)

    def _log_hook_output(self, phase: str, output: str):
        """Append to global hooks.log"""
        log_path = Path("/var/log/sven_hooks.log")
        try:
            with log_path.open("a") as f:
                f.write(f"\n--- {self.pkg_name} ({phase}) ---\n")
                f.write(output)
                f.write("\n")
        except OSError:
            pass
