[general]
install_root      = /
cache_dir         = /var/cache/sven
db_path           = /var/lib/sven
init_system       = sysvinit

[repos]
use_official      = true
use_aur           = true
aur_review        = prompt

[build]
parallel_jobs     = 1
keep_cache        = false

[download]
parallel_downloads = 2
mirror             = auto
